id: IF114C9C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:36:23+00:00'
last_modified: '2022-06-08T06:47:55.365493+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13819
  title: དབུ་མ་ལ་འཇུག་པའི་སྤྱི་དོན་དགོངས་པ་རབ་གསལ་གྱི་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5E00:
      image_group_id: I1KG14935
      title: ''
      total_pages: 342
      order: 1
      base_file: 5E00.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
